export { default as Login } from './Signin'
export { default as Signup } from './Signup'
export { default as Profile } from './Profile'
export { default as Register } from './Register'
export { default as Otp } from './Otp'
